module.exports = {
  FETCH_DEVICES: 'FETCH_DEVICES',
  RECEIVE_DEVICES: 'RECEIVE_DEVICES',
  RECEIVE_JOBS: 'RECEIVE_JOBS',
  ADD_JOB: 'ADD_JOB',
  UPDATE_MSG: 'UPDATE_MSG',
  CLEAN_MSG: 'CLEAN_MSG',
};
