module.exports = {
  FETCH_DEVICES: 'FETCH_DEVICES',
  RECEIVE_DEVICES: 'RECEIVE_DEVICES',
  RECEIVE_JOBS: 'RECEIVE_JOBS',
  ADD_JOB: 'ADD_JOB',
  UPDATE_JOB_MSG: 'UPDATE_JOB_MSG',
  CLEAN_JOB_MSG: 'CLEAN_JOB_MSG',
};
